# Update the tokens below with actual values.
# Tokenization is required to keep sensitive data from being committed to source.
FROM postgres:latest

#Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSOWRD mysecretpassword
ENV POSTGRES_DB hellodocker
