version: '2'

services:
  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: unless-stopped
    build: ./postgresql
    volumes_from:
      - data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
      - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge